[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "socib_rip_currents_detection"
description = "YOLO-obb based application for AI-driven rip current detection"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "AGPL-3.0-only"}
classifiers = [
    "Intended Audience :: Information Technology",
    "Intended Audience :: AI/ML/DL Researchers",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
dynamic = ["version", "dependencies"]

# Add author and author email here
authors = [
    {name = "Josep Oliver-Sanso", email = "joliver@socib.es"},
    {name = "Jesus Soriano-Gonzalez", email = "jsoriano@socib.es"},
    {name = "Albert Catala-Gonell", email = "albert.catala1@estudiant.uib.cat"}
]

[project.urls]
"Homepage" = "https://github.com/ai4os-hub/socib-rip-currents-detection"
"Bug Tracker" = "https://github.com/ai4os-hub/socib-rip-currents-detection/issues"

[tool.pytest.ini_options]
pythonpath = ["."]
env = ["DATA_PATH=tests/data", "MODELS_PATH=tests/models"]
addopts = "--import-mode=importlib"

[tool.setuptools]
packages = ["ai4os_yolo", "socib_rip_currents_detection.api"]

[tool.setuptools.package-dir]
"socib_rip_currents_detection.api" = "api"
"ai4os_yolo" = "ai4os_yolo"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
version = { file = "VERSION" }

[project.entry-points."deepaas.v2.model"]
socib_rip_currents_detection = "socib_rip_currents_detection.api"